### ISSUE TITLE
Add ability to deploy files out of a jar

### ISSUE THREAD

**Issue by paxtonhare** [rjrudin/ml-app-deployer#86]
Currently ml-app-deployer cannot deploy files out a jar. For data hub in a box I need to be able to deploy a directory of files ml-modules out of the jar resources.

**Comment by rjrudin** [comment]
@paxtonhare - will this be a static set of modules - i.e. will the data job software always know the names of the modules? If that's the case, you could just use the regular Java Client API and Spring's ClassPathResource class to get an InputStream to each known module and then load it. 

Also, this is filed in ml-app-deployer - do you need this capability for ml-config files as well? The Command classes in ml-app-deployer can only read from the filesystem, but the Manager classes (equivalent to the Java Client API) just deal with Strings, and so you could use the Manager classes plus Spring's ClassPathResource and its FileCopyUtils class, which assists with reading an InputStream into a String.

**Comment by paxtonhare** [comment]
It will know the names of the modules. I was hesitant to hard code the
names to avoid having to update a static list if new files get added, but
that seems like the easiest way here.

ml-config appears to be working for me despite the files living in a jar.

**Comment by rjrudin** [comment]
Will those modules all be in the same directory, such that a new method in DefaultModulesLoader would work like this:

Modules modules = new Modules()
modules.setAssetDirectories(new PathMachingResourcePatternResolver().getResources("classpath:/data-hub/ml-modules/lib/*.xqy"))
new DefaultModulesLoader().loadModules(databaseClient, modules)

This is a bit simpler than how DefaultModulesLoader currently works, where it's given a ModulesFinder that will find modules. But I think in your use case, you could populate a Modules instance yourself, and things will be good (one change I have to make is for Modules to have Lists of Resources instead of Lists of Files).

**Comment by paxtonhare** [comment]
turns out that ml-config isn't actually loading. I was somehow fooling myself into thinking it was working. Ideally we would be able to grab things like content-database.json from a jar.

**Comment by rjrudin** [comment]
@paxtonhare - are you aiming to create an AppConfig instance and then pass it to SimpleAppDeployer, along with a list of commands? 

Do you know the exact path of each config file that you need to load?

I am wondering if you could just use the Manager classes, though they don't know anything about AppConfig, nor do they support token replacement. I am guessing you want to use AppConfig and commands so you get token replacement.

**Comment by paxtonhare** [comment]
Actually, @rjrudin you have a good point. I was to narrow minded to realize that I could just call the stuff directly and bypass the conveniences of the json files. Let me try to do that.

**Comment by rjrudin** [comment]
@paxtonhare Any luck with this? I'm figuring out what should go into version 2.1.0, wondering if this should be included or if the priority has dropped.

**Comment by paxtonhare** [comment]
I think I'm good to go. I ended up just writing some code in the hub to
take care of this.

**Comment by rjrudin** [comment]
Okay, I'll close this.
